Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,72 +13,72 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    # - name: Build Angular App
-    #   working-directory: frontEnd-demo/demoFrontend
-    #   run: |
-    #     npm install
-    #     npm run build --prod
+    - name: Build Angular App
+      working-directory: frontEnd-demo/demoFrontend
+      run: |
+        npm install
+        npm run build --prod
 
-    # - name: Setup Java
-    #   uses: actions/setup-java@v3
-    #   with:
-    #     distribution: 'temurin'
-    #     java-version: '21'
+    - name: Setup Java
+      uses: actions/setup-java@v3
+      with:
+        distribution: 'temurin'
+        java-version: '21'
 
-    # - name: Build Spring Boot App
-    #   working-directory: demo/demo
-    #   run: ./mvnw clean package -DskipTests
+    - name: Build Spring Boot App
+      working-directory: demo/demo
+      run: ./mvnw clean package -DskipTests
 
-    # - name: Deploy to EC2 via WinRM
-    #   uses: appleboy/ssh-action@master
-    #   with:
-    #     host: ${{ secrets.EC2_HOST }}
-    #     username: ${{ secrets.EC2_USER }}
-    #     key: ${{ secrets.EC2_SSH_KEY }}
-    #     port: 22
-    #     script: |
-    #       cmd /c "(if not exist C:\application\frontend_new mkdir C:\application\frontend_new) & (if not exist C:\application\backend_new mkdir C:\application\backend_new)"
+    - name: Deploy to EC2 via WinRM
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        script: |
+          cmd /c "(if not exist C:\application\frontend_new mkdir C:\application\frontend_new) & (if not exist C:\application\backend_new mkdir C:\application\backend_new)"
 
-    # - name: Upload Angular frontend
-    #   uses: appleboy/scp-action@master
-    #   with:
-    #     host: ${{ secrets.EC2_HOST }}
-    #     username: ${{ secrets.EC2_USER }}
-    #     key: ${{ secrets.EC2_SSH_KEY }}
-    #     port: 22
-    #     source: "frontEnd-demo/demoFrontend/dist/demo-frontend/*"
-    #     target: "C:/application/FE/"
+    - name: Upload Angular frontend
+      uses: appleboy/scp-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        source: "frontEnd-demo/demoFrontend/dist/demo-frontend/*"
+        target: "C:/application/FE/"
 
-    # - name: Upload Spring Boot jar
-    #   uses: appleboy/scp-action@master
-    #   with:
-    #     host: ${{ secrets.EC2_HOST }}
-    #     username: ${{ secrets.EC2_USER }}
-    #     key: ${{ secrets.EC2_SSH_KEY }}
-    #     port: 22
-    #     source: "demo/demo/target/demo-0.0.1-SNAPSHOT.jar"
-    #     target: "C:/application/"
+    - name: Upload Spring Boot jar
+      uses: appleboy/scp-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        source: "demo/demo/target/demo-0.0.1-SNAPSHOT.jar"
+        target: "C:/application/"
 
-    # - name: Create folder "abc" in EC2 instance
-    #   uses: appleboy/ssh-action@master
-    #   with:
-    #     host: ${{ secrets.EC2_HOST }}
-    #     username: ${{ secrets.EC2_USER }}
-    #     key: ${{ secrets.EC2_SSH_KEY }}
-    #     port: 22
-    #     script: |
-    #       if not exist C:\application\abc mkdir C:\application\abc
+    - name: Create folder "abc" in EC2 instance
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        script: |
+          if not exist C:\application\abc mkdir C:\application\abc
 
 
-    # - name: Replace old app and restart services
-    #   uses: appleboy/ssh-action@master
-    #   with:
-    #     host: ${{ secrets.EC2_HOST }}
-    #     username: ${{ secrets.EC2_USER }}
-    #     key: ${{ secrets.EC2_SSH_KEY }}
-    #     port: 22
-    #     script: |
-    #       cmd /c "(taskkill /F /IM java.exe || echo "Java process not found, continuing...") & (timeout /t 10 || echo "waiting, continuing...") & (if not exist "C:/application/abcd" mkdir "C:/application/abcd") & (dir frontEnd-demo/demoFrontend/dist/demo-frontend) & (cd C:/application ) & (move /Y C:\application\FE\frontEnd-demo\demoFrontend\dist\demo-frontend\* C:\application\FE\demo-frontend\ || echo MOVE FAILED) & (move /Y C:\application\demo\demo\target\demo-0.0.1-SNAPSHOT.jar C:\application\ || echo MOVE FAILED) & (cd C:/application) & (C:\application\runJar.bat) & (timeout /t 25 || echo "waiting for jar running, continuing...") & (cd C:\application\nginx-1.28.0) & (nginx.exe -s reload) & (timeout /t 5 || echo "waiting for jar running, continuing...") "
+    - name: Replace old app and restart services
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        script: |
+          cmd /c "(taskkill /F /IM java.exe || echo "Java process not found, continuing...") & (timeout /t 10 || echo "waiting, continuing...") & (if not exist "C:/application/abcd" mkdir "C:/application/abcd") & (dir frontEnd-demo/demoFrontend/dist/demo-frontend) & (cd C:/application ) & (move /Y C:\application\FE\frontEnd-demo\demoFrontend\dist\demo-frontend\* C:\application\FE\demo-frontend\ || echo MOVE FAILED) & (move /Y C:\application\demo\demo\target\demo-0.0.1-SNAPSHOT.jar C:\application\ || echo MOVE FAILED) & (cd C:/application) & (C:\application\runJar.bat) & (timeout /t 25 || echo "waiting for jar running, continuing...") & (cd C:\application\nginx-1.28.0) & (nginx.exe -s reload) & (timeout /t 5 || echo "waiting for jar running, continuing...") "
 
     - name: Run Springboot Jar
       uses: appleboy/ssh-action@master
@@ -87,8 +87,8 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         port: 22
-        script: |
-          cmd /c "(cd C:/application) & (C:\application\runJar.bat)" 
+        # script: |
+        #   cmd /c "(cd C:/application) & (C:\application\runJar.bat)" 
         inlineScript: |
           java -jar C:\application\demo-0.0.1-SNAPSHOT.jar   
     
